#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSOR_DIR)		+= sensors_core.o

# accelerometer_sensor
obj-$(CONFIG_SENSORS_K3DH)		+= k3dh.o
obj-$(CONFIG_SENSORS_BMA254)	+= bma254_driver.o
